CREATE TABLE category (
    reference SERIAL PRIMARY KEY,
    parent VARCHAR(255) NOT NULL,
    sub VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);