CREATE TABLE shop.category (
    reference SERIAL PRIMARY KEY,
    parent VARCHAR(255) NOT NULL,
    sub VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);