INSERT INTO category (parent, sub) VALUES
-- Tops
('TOPS', 'T-SHIRT'),
('TOPS', 'SHIRT'),
('TOPS', 'BLOUSE'),
('TOPS', 'TANK TOP'),
('TOPS', 'SWEATER'),
('TOPS', 'HOODIE'),

-- Bottoms
('BOTTOMS', 'JEANS'),
('BOTTOMS', 'TROUSERS'),
('BOTTOMS', 'SHORTS'),
('BOTTOMS', 'SKIRT'),
('BOTTOMS', 'LEGGINGS'),

-- Outerwear
('OUTERWEAR', 'JACKET'),
('OUTERWEAR', 'COAT'),
('OUTERWEAR', 'BLAZER'),
('OUTERWEAR', 'PARKA'),
('OUTERWEAR', 'RAINCOAT'),

-- Dresses & Jumpsuits
('DRESSES', 'CASUAL'),
('DRESSES', 'EVENING'),
('DRESSES', 'GOWN'),
('DRESSES', 'JUMPSUIT'),
('DRESSES', 'ROMPER'),

-- Bags
('BAGS', 'BACKPACK'),
('BAGS', 'HANDBAG'),
('BAGS', 'CROSSBODY'),
('BAGS', 'TOTE'),
('BAGS', 'CLUTCH'),

-- Shoes
('SHOES', 'SNEAKERS'),
('SHOES', 'BOOTS'),
('SHOES', 'HEELS'),
('SHOES', 'FLATS'),
('SHOES', 'SANDALS'),

-- Accessories
('ACCESSORIES', 'BELT'),
('ACCESSORIES', 'SCARF'),
('ACCESSORIES', 'HAT'),
('ACCESSORIES', 'GLOVES'),
('ACCESSORIES', 'SUNGLASSES'),
('ACCESSORIES', 'JEWELRY'),

-- Undergarments
('UNDERGARMENTS', 'BRA'),
('UNDERGARMENTS', 'UNDERWEAR'),
('UNDERGARMENTS', 'SOCKS'),
('UNDERGARMENTS', 'THERMALS');
