INSERT INTO shop."articleCategory" ("c1", "c2", "c3", "c4", "c5", "c6") VALUES
('CLOTHES', 'TOPS', 'T-SHIRT', NULL, NULL, NULL),
('CLOTHES', 'TOPS', 'BLOUSE', NULL, NULL, NULL),
('CLOTHES', 'TOPS', 'TANK-TOP', NULL, NULL, NULL),
('CLOTHES', 'TOPS', 'SWEATER', NULL, NULL, NULL),
('CLOTHES', 'TOPS', 'HOODIE', NULL, NULL, NULL),
('CLOTHES', 'TOPS', NULL, NULL, NULL, NULL),

('CLOTHES', 'BOTTOMS', 'JEANS', NULL, NULL, NULL),
('CLOTHES', 'BOTTOMS', 'TROUSERS', NULL, NULL, NULL),
('CLOTHES', 'BOTTOMS', 'SHORTS', NULL, NULL, NULL),
('CLOTHES', 'BOTTOMS', 'SKIRT', NULL, NULL, NULL),
('CLOTHES', 'BOTTOMS', 'LEGGINGS', NULL, NULL, NULL),

('CLOTHES', 'OUTERWEAR', 'JACKET', NULL, NULL, NULL),
('CLOTHES', 'OUTERWEAR', 'COAT', NULL, NULL, NULL), 
('CLOTHES', 'OUTERWEAR', 'BLAZER', NULL, NULL, NULL), 
('CLOTHES', 'OUTERWEAR', 'PARKA', NULL, NULL, NULL), 
('CLOTHES', 'OUTERWEAR', 'RAINCOAT', NULL, NULL, NULL), 

('CLOTHES', 'DRESSES', 'CASUAL', NULL, NULL, NULL),
('CLOTHES', 'DRESSES', 'EVENING', NULL, NULL, NULL),
('CLOTHES', 'DRESSES', 'GOWN', NULL, NULL, NULL),

('CLOTHES', 'BAGS', 'BACKPACK', NULL, NULL, NULL),
('CLOTHES', 'BAGS', 'HANDBAG', NULL, NULL, NULL),
('CLOTHES', 'BAGS', 'CROSSBODY', NULL, NULL, NULL),
('CLOTHES', 'BAGS', 'TOTE', NULL, NULL, NULL),
('CLOTHES', 'BAGS', 'CLUTCH', NULL, NULL, NULL),

('CLOTHES', 'SHOES', 'SNEAKERS', NULL, NULL, NULL),
('CLOTHES', 'SHOES', 'BOOTS', NULL, NULL, NULL),
('CLOTHES', 'SHOES', 'HEELS', NULL, NULL, NULL),
('CLOTHES', 'SHOES', 'FLATS', NULL, NULL, NULL),
('CLOTHES', 'SHOES', 'SANDALS', NULL, NULL, NULL),

('CLOTHES', 'ACCESSORIES', 'BELT', NULL, NULL, NULL),
('CLOTHES', 'ACCESSORIES', 'SCARF', NULL, NULL, NULL),
('CLOTHES', 'ACCESSORIES', 'HAT', NULL, NULL, NULL),
('CLOTHES', 'ACCESSORIES', 'GLOVES', NULL, NULL, NULL),
('CLOTHES', 'ACCESSORIES', 'SUNGLASSES', NULL, NULL, NULL),
('CLOTHES', 'ACCESSORIES', 'JEWELRY', NULL, NULL, NULL),

('CLOTHES', 'UNDERGARMENTS', 'BRA', NULL, NULL, NULL),
('CLOTHES', 'UNDERGARMENTS', 'UNDERWEAR', NULL, NULL, NULL),
('CLOTHES', 'UNDERGARMENTS', 'SOCKS', NULL, NULL, NULL),
('CLOTHES', 'UNDERGARMENTS', 'THERMALS', NULL, NULL, NULL);