CREATE TYPE shop.availability AS ENUM (
  'AVAILABLE',
  'UNAVAILABLE',
  'DAMAGED',
  'FOR_RENT',
  'FOR_SALE',
  'INACTIVE',
  'IN_TRANSIT',
  'OUT_OF_STOCK',
  'RENTED',
  'RESERVED',
  'RETURNED',
  'SOLD'
);
