DROP TYPE IF EXISTS shop.brand;
CREATE TYPE shop.brand AS ENUM (
  'Unbranded',
  'Roberto Cavali', 
  'Just Cavali', 
  'Dolce & Gabbana', 
  'Dior', 
  'John Galliano',
  'Versace',
  'Blumarine',
  'Moschino',
  'Alexander McQueen',
  'Chloé',
  'Jean Paul Gaultier',
  'Betsey Johnson',
  'Channel',
  'Gucci',
  'Prada',
  'Cop Copine',
  'Emilio Pucci',
  'Escada',
  'Fendi',
  'Muxart',
  'Gaetano Navarra',
  'Gianfranco Ferre',
  'Giuseppe Zanotti',
  'Fayazi',
  'Maison Margiela',
  'Lexus'
);