CREATE TYPE shop.brand AS ENUM (
  'Alexander McQueen',
  'Betsey Johnson',
  'Blumarine',
  'Channel',
  'Chloé',
  'Cop Copine',
  'Dior',
  'Dolce & Gabbana',
  'Emilio Pucci',
  'Escada',
  'Fayazi',
  'Fendi',
  'Gaetano Navarra',
  'Gianfranco Ferre',
  'Giuseppe Zanotti',
  'Gucci',
  'Jean Paul Gaultier',
  'John Galliano',
  'Just Cavali',
  'Lexus',
  'Maison Margiela',
  'Moschino',
  'Muxart',
  'Prada',
  'Roberto Cavali',
  'Unbranded',
  'Versace'
);
