CREATE TABLE shop.article_sub_category (
	reference TEXT PRIMARY KEY NOT NULL UNIQUE
);

INSERT INTO shop.article_sub_category (reference) VALUES
('T-SHIRT'),
('SHIRT'),
('BLOUSE'),
('TANK TOP'),
('SWEATER'),
('HOODIE'),
('JEANS'),
('TROUSERS'),
('SHORTS'),
('SKIRT'),
('LEGGINGS'),
('JACKET'),
('COAT'),
('BLAZER'),
('PARKA'),
('RAINCOAT'),
('CASUAL'),
('EVENING'),
('GOWN'),
('JUMPSUIT'),
('ROMPER'),
('BACKPACK'),
('HANDBAG'),
('CROSSBODY'),
('TOTE'),
('CLUTCH'),
('SNEAKERS'),
('BOOTS'),
('HEELS'),
('FLATS'),
('SANDALS'),
('BELT'),
('SCARF'),
('HAT'),
('GLOVES'),
('SUNGLASSES'),
('JEWELRY'),
('BRA'),
('UNDERWEAR'),
('SOCKS'),
('THERMALS');