import express from "express";
import { Router } from "express";
import { instanceToPlain, plainToInstance } from "class-transformer";

import { getPgClient } from "../../utils/database";
import {
  ExpectedRequest,
  ExpectedResponse,
  GLOBAL_AUTOGENERATED_FIELDS,
} from "../server";
import { User } from "../classes/transformer-classes";
import { QueryResult } from "pg";

const userRouter: Router = express.Router();

// Handeling the route parameters
userRouter.param(
  "id",
  (req: ExpectedRequest, res: ExpectedResponse, next, value) => {
    req.id = value;
    next();
  }
);

// Handeling the retrieval of the pgClient
userRouter.use((req: ExpectedRequest, res: ExpectedResponse, next) => {
  try {
    req.pgClient = getPgClient();
  } catch (error) {
    res.status(500).json({
      error: `Encountered an error when getting the postgresql client: ${error}`,
    });
    res.end();
  }
  next();
});

// Handle request on the param route
userRouter
  .route("/:id")
  .get((req: ExpectedRequest, res: ExpectedResponse) => {})
  .post((req: ExpectedRequest, res: ExpectedResponse) => {})
  .put((req: ExpectedRequest, res: ExpectedResponse) => {})
  .delete((req: ExpectedRequest, res: ExpectedResponse) => {});

// Handle request on the main route
userRouter
  .route("/")
  .get(async (req: ExpectedRequest, res: ExpectedResponse) => {
    // Retrieve the query params
    const limit: string | undefined = req.limit;
    const offset: string | undefined = req.limit;

    // Format the database query
    const query: string = `
SELECT *
FROM shop.user
ORDER BY updated_at DESC
${limit ? "LIMIT " + limit + (offset ? " OFFSET " + offset : "") : ""};
    `;

    // Run the query on the database
    try {
      const queryResult: QueryResult = await req.pgClient!.query(query);
      res.status(200).json(queryResult.rows);
      res.end();
    } catch (error) {
      res.status(400).json({
        error: `Failed to execute the query on the database: ${error}`,
        query: query,
      });
      res.end();
    }
  })
  .post(async (req: ExpectedRequest, res: ExpectedResponse) => {
    // Retrieve the request body
    const body: any = req.body;

    // Verify whether the inputs is in array
    if (!Array.isArray(body)) {
      res.status(400).json({ error: "Expected an array of users" });
      res.end();
    }

    // Convert plain objects into instances
    let users: User[] = [];
    for (let i: number = 0; i < body.length; i++) {
      const plain: any = body[i];
      try {
        const user: User = plainToInstance(User, plain);
        users.push(user);
      } catch (error) {
        res.status(400).json({
          error: `Failed to tranform the plain object into an User instance: ${error}`,
          record: plain,
        });
        res.end();
      }
    }

    // Retrieve the expected fields to insert
    let fields: string[] = Object.keys(users[0]);
    fields = fields.filter(
      (field) => !GLOBAL_AUTOGENERATED_FIELDS.includes(field)
    );

    // Reconvert the instances to plain
    let plains: Record<string, any>[] = [];
    for (let i: number = 0; i < users.length; i++) {
      const user: User = users[i];
      const plain: Record<string, any> = instanceToPlain(user);
      plains.push(plain);
    }

    // Retrieve all the record values
    let valuesRecords: string[] = [];
    for (let i: number = 0; i < plains.length; i++) {
      const plain: Record<string, any> = plains[i];
      const valuesRecord: string[] = fields.map((field) =>
        plain[field] === undefined
          ? "DEFAULT"
          : plain[field] === null
          ? "NULL"
          : typeof plain[field] === "string"
          ? `'${plain[field]}'`
          : plain[field]
      );
      valuesRecords.push(`(${valuesRecord.join(", ")})`);
    }

    // Format the database query
    const query: string = `
INSERT INTO shop.user (${fields.join(", ")})
VALUES
${valuesRecords.join(",\n")}
RETURNING *;
    `;

    // Run the query on the database
    try {
      const queryResult: QueryResult = await req.pgClient!.query(query);
      res.status(200).json(queryResult.rows);
      res.end();
    } catch (error) {
      res.status(400).json({
        error: `Failed to execute the query on the database: ${error}`,
        query: query,
      });
      res.end();
    }
  })
  .put(async (req: ExpectedRequest, res: ExpectedResponse) => {
    // Retrieve the request body
    const body: any = req.body;

    // Verify whether the inputs is in array
    if (!Array.isArray(body)) {
      res.status(400).json({ error: "Expected an array of users" });
      res.end();
    }

    // Convert plain objects into instances
    let users: User[] = [];
    for (let i: number = 0; i < body.length; i++) {
      const plain: any = body[i];
      try {
        const user: User = plainToInstance(User, plain);
        users.push(user);
      } catch (error) {
        res.status(400).json({
          error: `Failed to tranform the plain object into an User instance: ${error}`,
          record: plain,
        });
        res.end();
      }
    }

    // Retrieve the expected fields to insert
    let fields: string[] = Object.keys(users[0]);
    fields = fields.filter(
      (field) => !GLOBAL_AUTOGENERATED_FIELDS.includes(field)
    );

    // Reconvert the instances to plain
    let plains: Record<string, any>[] = [];
    for (let i: number = 0; i < users.length; i++) {
      const user: User = users[i];
      const plain: Record<string, any> = instanceToPlain(user);
      plains.push(plain);
    }

    // Retrieve all the record values
    let valuesRecords: string[] = [];
    for (let i: number = 0; i < plains.length; i++) {
      const plain: Record<string, any> = plains[i];
      const valuesRecord: string[] = fields.map((field) =>
        plain[field] === null
          ? "NULL"
          : typeof plain[field] === "string"
          ? `'${plain[field]}'`
          : plain[field]
      );
      valuesRecords.push(`(${valuesRecord.join(", ")})`);
    }

    // Retrieve all the fields to update
    const updateFields: string[] = [];
    for (let i: number = 0; i < fields.length; i++) {
      const field: string = fields[i];
      if (field === "reference") {
        continue;
      }

      updateFields.push(`${field} = temp_updates.${field}`);
    }

    // Format the database query
    const query: string = `
DROP TABLE IF EXISTS temp_updates;

CREATE TEMP TABLE temp_updates 
(LIKE shop."user" INCLUDING DEFAULTS INCLUDING CONSTRAINTS);

INSERT INTO temp_updates (${fields.join(", ")})
VALUES
${valuesRecords.join(",\n")};

UPDATE shop."user"
SET
${updateFields.join(",\n")}
FROM temp_updates
WHERE "user".reference = temp_updates.reference
RETURNING "user".*;
    `;
    console.log(query);

    // Run the query on the database
    try {
      const queryResult: QueryResult = await req.pgClient!.query(query);
      console.log(queryResult.rows);
      res.status(200).json(queryResult.rows);
      res.end();
    } catch (error) {
      res.status(400).json({
        error: `Failed to execute the query on the database: ${error}`,
        query: query,
      });
      res.end();
    }
  })
  .delete((req: ExpectedRequest, res: ExpectedResponse) => {});

export default userRouter;
